// Mocks generated by Mockito 5.3.2 from annotations
// in report_it/test/testing_LoginSPID/LoginSPID_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:report_it/data/models/AutenticazioneDAO.dart' as _i2;
import 'package:report_it/domain/entity/entity_GA/operatoreCUP_entity.dart'
    as _i7;
import 'package:report_it/domain/entity/entity_GA/spid_entity.dart' as _i4;
import 'package:report_it/domain/entity/entity_GA/uffPolGiud_entity.dart'
    as _i6;
import 'package:report_it/domain/entity/entity_GA/utente_entity.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AutenticazioneDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutenticazioneDAO extends _i1.Mock implements _i2.AutenticazioneDAO {
  MockAutenticazioneDAO() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.SPID?> RetrieveSPIDByEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveSPIDByEmail,
          [email],
        ),
        returnValue: _i3.Future<_i4.SPID?>.value(),
      ) as _i3.Future<_i4.SPID?>);
  @override
  _i3.Future<_i5.Utente?> RetrieveUtenteByID(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveUtenteByID,
          [uid],
        ),
        returnValue: _i3.Future<_i5.Utente?>.value(),
      ) as _i3.Future<_i5.Utente?>);
  @override
  _i3.Future<_i4.SPID?> RetrieveSPIDByID(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #RetrieveSPIDByID,
          [uid],
        ),
        returnValue: _i3.Future<_i4.SPID?>.value(),
      ) as _i3.Future<_i4.SPID?>);
  @override
  _i3.Future<_i6.UffPolGiud?> RetrieveUffPolGiudByID(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveUffPolGiudByID,
          [uid],
        ),
        returnValue: _i3.Future<_i6.UffPolGiud?>.value(),
      ) as _i3.Future<_i6.UffPolGiud?>);
  @override
  _i3.Future<_i7.OperatoreCUP?> RetrieveCUPByID(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveCUPByID,
          [uid],
        ),
        returnValue: _i3.Future<_i7.OperatoreCUP?>.value(),
      ) as _i3.Future<_i7.OperatoreCUP?>);
  @override
  _i3.Future<List<_i5.Utente?>> RetrieveAllUtente() => (super.noSuchMethod(
        Invocation.method(
          #RetrieveAllUtente,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Utente?>>.value(<_i5.Utente?>[]),
      ) as _i3.Future<List<_i5.Utente?>>);
  @override
  _i3.Future<List<_i4.SPID?>> RetrieveAllSPID() => (super.noSuchMethod(
        Invocation.method(
          #RetrieveAllSPID,
          [],
        ),
        returnValue: _i3.Future<List<_i4.SPID?>>.value(<_i4.SPID?>[]),
      ) as _i3.Future<List<_i4.SPID?>>);
  @override
  _i3.Future<List<_i6.UffPolGiud?>> RetrieveAllUffPolGiud() =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveAllUffPolGiud,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.UffPolGiud?>>.value(<_i6.UffPolGiud?>[]),
      ) as _i3.Future<List<_i6.UffPolGiud?>>);
  @override
  _i3.Future<List<_i7.OperatoreCUP?>> RetrieveAllOperatoreCUP() =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveAllOperatoreCUP,
          [],
        ),
        returnValue:
            _i3.Future<List<_i7.OperatoreCUP?>>.value(<_i7.OperatoreCUP?>[]),
      ) as _i3.Future<List<_i7.OperatoreCUP?>>);
}

/// A class which mocks [AutenticazioneDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutenticazioneDAORelaxed extends _i1.Mock
    implements _i2.AutenticazioneDAO {
  MockAutenticazioneDAORelaxed() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.SPID?> RetrieveSPIDByEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveSPIDByEmail,
          [email],
        ),
        returnValue: _i3.Future<_i4.SPID?>.value(),
      ) as _i3.Future<_i4.SPID?>);
  @override
  _i3.Future<_i5.Utente?> RetrieveUtenteByID(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveUtenteByID,
          [uid],
        ),
        returnValue: _i3.Future<_i5.Utente?>.value(),
      ) as _i3.Future<_i5.Utente?>);
  @override
  _i3.Future<_i4.SPID?> RetrieveSPIDByID(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #RetrieveSPIDByID,
          [uid],
        ),
        returnValue: _i3.Future<_i4.SPID?>.value(),
      ) as _i3.Future<_i4.SPID?>);
  @override
  _i3.Future<_i6.UffPolGiud?> RetrieveUffPolGiudByID(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveUffPolGiudByID,
          [uid],
        ),
        returnValue: _i3.Future<_i6.UffPolGiud?>.value(),
      ) as _i3.Future<_i6.UffPolGiud?>);
  @override
  _i3.Future<_i7.OperatoreCUP?> RetrieveCUPByID(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveCUPByID,
          [uid],
        ),
        returnValue: _i3.Future<_i7.OperatoreCUP?>.value(),
      ) as _i3.Future<_i7.OperatoreCUP?>);
  @override
  _i3.Future<List<_i5.Utente?>> RetrieveAllUtente() => (super.noSuchMethod(
        Invocation.method(
          #RetrieveAllUtente,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Utente?>>.value(<_i5.Utente?>[]),
      ) as _i3.Future<List<_i5.Utente?>>);
  @override
  _i3.Future<List<_i4.SPID?>> RetrieveAllSPID() => (super.noSuchMethod(
        Invocation.method(
          #RetrieveAllSPID,
          [],
        ),
        returnValue: _i3.Future<List<_i4.SPID?>>.value(<_i4.SPID?>[]),
      ) as _i3.Future<List<_i4.SPID?>>);
  @override
  _i3.Future<List<_i6.UffPolGiud?>> RetrieveAllUffPolGiud() =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveAllUffPolGiud,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.UffPolGiud?>>.value(<_i6.UffPolGiud?>[]),
      ) as _i3.Future<List<_i6.UffPolGiud?>>);
  @override
  _i3.Future<List<_i7.OperatoreCUP?>> RetrieveAllOperatoreCUP() =>
      (super.noSuchMethod(
        Invocation.method(
          #RetrieveAllOperatoreCUP,
          [],
        ),
        returnValue:
            _i3.Future<List<_i7.OperatoreCUP?>>.value(<_i7.OperatoreCUP?>[]),
      ) as _i3.Future<List<_i7.OperatoreCUP?>>);
}
